stages:
  - test 
  - deploy 

unit-test:
  image: python:3.8-buster
  stage: test
  variables:
    DB_STRING_CONNECTION: '"$DB_STRING_CONNECTION"'
    DB_DATABASE: '"$DB_DATABASE"'
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - export PYTHONPATH=.
    - pytest --cov-report term-missing:skip-covered --cov=niched/ test/unit_tests/

integration-test:
  image: python:3.8-buster
  stage: test
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - export PYTHONPATH=.
    - pytest --cov-report term-missing:skip-covered --cov=niched/ test/integration_tests/

heroku-deploy:
  image: ruby:3.0.1
  stage: deploy 
  script:
    - gem install dpl
    - dpl --provider=heroku --app=niched-api --api-key=$HEROKU_SERVER_API_KEY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

